// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// StabilizedScaling_Rcpp
Rcpp::List StabilizedScaling_Rcpp(const Eigen::Map<Eigen::MatrixXd> costMatrix, const Eigen::Map<Eigen::VectorXd> supply, const Eigen::Map<Eigen::VectorXd> demand, const double lambdaSupply, const double alphaSupply, const double betaSupply, const double lambdaDemand, const double alphaDemand, const double betaDemand, const int DivSupply, const int DivDemand, const size_t iterMax, const Eigen::Map<Eigen::VectorXd> epsvec, const double tol);
RcppExport SEXP _unbalancedTransport_StabilizedScaling_Rcpp(SEXP costMatrixSEXP, SEXP supplySEXP, SEXP demandSEXP, SEXP lambdaSupplySEXP, SEXP alphaSupplySEXP, SEXP betaSupplySEXP, SEXP lambdaDemandSEXP, SEXP alphaDemandSEXP, SEXP betaDemandSEXP, SEXP DivSupplySEXP, SEXP DivDemandSEXP, SEXP iterMaxSEXP, SEXP epsvecSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type costMatrix(costMatrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type supply(supplySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type demand(demandSEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaSupply(lambdaSupplySEXP);
    Rcpp::traits::input_parameter< const double >::type alphaSupply(alphaSupplySEXP);
    Rcpp::traits::input_parameter< const double >::type betaSupply(betaSupplySEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaDemand(lambdaDemandSEXP);
    Rcpp::traits::input_parameter< const double >::type alphaDemand(alphaDemandSEXP);
    Rcpp::traits::input_parameter< const double >::type betaDemand(betaDemandSEXP);
    Rcpp::traits::input_parameter< const int >::type DivSupply(DivSupplySEXP);
    Rcpp::traits::input_parameter< const int >::type DivDemand(DivDemandSEXP);
    Rcpp::traits::input_parameter< const size_t >::type iterMax(iterMaxSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type epsvec(epsvecSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(StabilizedScaling_Rcpp(costMatrix, supply, demand, lambdaSupply, alphaSupply, betaSupply, lambdaDemand, alphaDemand, betaDemand, DivSupply, DivDemand, iterMax, epsvec, tol));
    return rcpp_result_gen;
END_RCPP
}
// Sinkhorn_Rcpp
Rcpp::List Sinkhorn_Rcpp(Rcpp::NumericMatrix& costMatrix, const Rcpp::NumericVector& supply, const Rcpp::NumericVector& demand, const double lambdaSupply, const double param1Supply, const double param2Supply, const double lambdaDemand, const double param1Demand, const double param2Demand, const int DivSupply, const int DivDemand, const size_t iterMax, const Rcpp::NumericVector& epsvec, const double tol, Eigen::Map<Eigen::MatrixXd> supdem);
RcppExport SEXP _unbalancedTransport_Sinkhorn_Rcpp(SEXP costMatrixSEXP, SEXP supplySEXP, SEXP demandSEXP, SEXP lambdaSupplySEXP, SEXP param1SupplySEXP, SEXP param2SupplySEXP, SEXP lambdaDemandSEXP, SEXP param1DemandSEXP, SEXP param2DemandSEXP, SEXP DivSupplySEXP, SEXP DivDemandSEXP, SEXP iterMaxSEXP, SEXP epsvecSEXP, SEXP tolSEXP, SEXP supdemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type costMatrix(costMatrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type supply(supplySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type demand(demandSEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaSupply(lambdaSupplySEXP);
    Rcpp::traits::input_parameter< const double >::type param1Supply(param1SupplySEXP);
    Rcpp::traits::input_parameter< const double >::type param2Supply(param2SupplySEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaDemand(lambdaDemandSEXP);
    Rcpp::traits::input_parameter< const double >::type param1Demand(param1DemandSEXP);
    Rcpp::traits::input_parameter< const double >::type param2Demand(param2DemandSEXP);
    Rcpp::traits::input_parameter< const int >::type DivSupply(DivSupplySEXP);
    Rcpp::traits::input_parameter< const int >::type DivDemand(DivDemandSEXP);
    Rcpp::traits::input_parameter< const size_t >::type iterMax(iterMaxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type epsvec(epsvecSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type supdem(supdemSEXP);
    rcpp_result_gen = Rcpp::wrap(Sinkhorn_Rcpp(costMatrix, supply, demand, lambdaSupply, param1Supply, param2Supply, lambdaDemand, param1Demand, param2Demand, DivSupply, DivDemand, iterMax, epsvec, tol, supdem));
    return rcpp_result_gen;
END_RCPP
}
// Hausdorff_Vec_Rcpp
Rcpp::NumericVector Hausdorff_Vec_Rcpp(const Rcpp::NumericMatrix costMatrix, const Rcpp::NumericVector& distribution, const Rcpp::NumericVector& f, const double lambda, const double param1, const double param2, const int Div, const double eps);
RcppExport SEXP _unbalancedTransport_Hausdorff_Vec_Rcpp(SEXP costMatrixSEXP, SEXP distributionSEXP, SEXP fSEXP, SEXP lambdaSEXP, SEXP param1SEXP, SEXP param2SEXP, SEXP DivSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type costMatrix(costMatrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type distribution(distributionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type f(fSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type param1(param1SEXP);
    Rcpp::traits::input_parameter< const double >::type param2(param2SEXP);
    Rcpp::traits::input_parameter< const int >::type Div(DivSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Hausdorff_Vec_Rcpp(costMatrix, distribution, f, lambda, param1, param2, Div, eps));
    return rcpp_result_gen;
END_RCPP
}
// treegkr_Rcpp
Rcpp::List treegkr_Rcpp(Rcpp::List& tree, const Rcpp::NumericVector& supply, const Rcpp::NumericVector& demand, const Rcpp::NumericVector& creation, const Rcpp::NumericVector& destruction);
RcppExport SEXP _unbalancedTransport_treegkr_Rcpp(SEXP treeSEXP, SEXP supplySEXP, SEXP demandSEXP, SEXP creationSEXP, SEXP destructionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type supply(supplySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type demand(demandSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type creation(creationSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type destruction(destructionSEXP);
    rcpp_result_gen = Rcpp::wrap(treegkr_Rcpp(tree, supply, demand, creation, destruction));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_unbalancedTransport_StabilizedScaling_Rcpp", (DL_FUNC) &_unbalancedTransport_StabilizedScaling_Rcpp, 14},
    {"_unbalancedTransport_Sinkhorn_Rcpp", (DL_FUNC) &_unbalancedTransport_Sinkhorn_Rcpp, 15},
    {"_unbalancedTransport_Hausdorff_Vec_Rcpp", (DL_FUNC) &_unbalancedTransport_Hausdorff_Vec_Rcpp, 8},
    {"_unbalancedTransport_treegkr_Rcpp", (DL_FUNC) &_unbalancedTransport_treegkr_Rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_unbalancedTransport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
